/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-07-16 07:02:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.trip;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class tripView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/trip/../../views/common/footer.jsp", Long.valueOf(1626285298671L));
    _jspx_dependants.put("/views/common/menubar.jsp", Long.valueOf(1626405854230L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\">\r\n");
      out.write("<title>topp</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<!-- 	//import=\"member.model.vo.Member\"   -->\r\n");

//로그인 확인을 위해서 내장된 session 객체를 이용
//Member loginMember = (Member)session.getAttribute("loginMember");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#topping_wrap1 {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#topping_header {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main_menu {\r\n");
      out.write("	border-bottom: 1px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main_menu_w1230 {\r\n");
      out.write("	width: 1230px;\r\n");
      out.write("	height: 75px;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	clear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#headerLogo img {\r\n");
      out.write("	width: 220px;\r\n");
      out.write("	height: 60px;\r\n");
      out.write("	margin-top: 4px;\r\n");
      out.write("	float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#serviceLogo img {\r\n");
      out.write("	float: right;\r\n");
      out.write("	margin-top: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#loginLogo img {\r\n");
      out.write("	float: right;\r\n");
      out.write("	margin-top: 12px;\r\n");
      out.write("	margin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menubar {\r\n");
      out.write("	width: 740px;\r\n");
      out.write("	line-height: 75px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menubar li {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	margin-right: 45px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".middle_area {\r\n");
      out.write("	display: block;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menuLink {\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"topping_wrap1\">\r\n");
      out.write("		<div id=\"topping_header\">\r\n");
      out.write("			<div class=\"main_menu\">\r\n");
      out.write("				<div class=\"main_menu_w1230\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<a href=\"http://localhost:8808/topp/\" id=\"headerLogo\"> <img\r\n");
      out.write("							src=\"/topp/resources/images/toppingLogo.png\">\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"middle_area\">\r\n");
      out.write("\r\n");
      out.write("						<ul class=\"menubar\">\r\n");
      out.write("							<li><a class=\"menuLink\" href=\"/topp/views/trip/tripView.jsp\">여행정보 검색</a></li>\r\n");
      out.write("							<li><a class=\"menuLink\" href=\"#\">여행일기</a></li>\r\n");
      out.write("							<li><a class=\"menuLink\" href=\"#\">트립박스</a></li>\r\n");
      out.write("							<li><a class=\"menuLink\" href=\"#\">마이페이지</a></li>\r\n");
      out.write("							<li><a class=\"menuLink\" href=\"#\">커뮤니티</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("\r\n");
      out.write("						<div>\r\n");
      out.write("							<a href=\"http://localhost:8808/topp/\" id=\"serviceLogo\"> <img\r\n");
      out.write("								src=\"/topp/resources/images/toppingService.png\">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div>\r\n");
      out.write("							<a href=\"http://localhost:8808/topp/\" id=\"loginLogo\"> <img\r\n");
      out.write("								src=\"/topp/resources/images/toppingLogin.png\">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</header>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<h1 style=\"text-align: center;\">\r\n");
      out.write("		여행검색 페이지<i class=\"bi bi-heart-fill\"\r\n");
      out.write("			style=\"font-size: 2rem; color: Red;\"></i>\r\n");
      out.write("	</h1>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<footer>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>topping</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".footer-clean {\r\n");
      out.write("  \r\n");
      out.write("  padding:50px 0;\r\n");
      out.write("  background-color:#fff;\r\n");
      out.write("  color:#4b4c4d;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-clean h3 {\r\n");
      out.write("  margin-top:0;\r\n");
      out.write("  margin-bottom:12px;\r\n");
      out.write("  font-weight:bold;\r\n");
      out.write("  font-size:16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-clean ul {\r\n");
      out.write("  padding:0;\r\n");
      out.write("  list-style:none;\r\n");
      out.write("  line-height:1.6;\r\n");
      out.write("  font-size:14px;\r\n");
      out.write("  margin-bottom:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-clean a {\r\n");
      out.write("  color:inherit;\r\n");
      out.write("  text-decoration:none;\r\n");
      out.write("  opacity:0.8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-clean ul a:hover {\r\n");
      out.write("  opacity:1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-clean .item.social {\r\n");
      out.write("  text-align:right;\r\n");
      out.write(" \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width:767px) {\r\n");
      out.write("  .footer-all .item {\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    padding-bottom:20px;\r\n");
      out.write("    \r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("  .footer-all .item.social {\r\n");
      out.write("    text-align:center;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-clean .item.social > a {\r\n");
      out.write("  font-size:24px;\r\n");
      out.write("  width:40px;\r\n");
      out.write("  height:40px;\r\n");
      out.write("  line-height:40px;\r\n");
      out.write("  display:inline-block;\r\n");
      out.write("  text-align:center;\r\n");
      out.write("  border-radius:50%;\r\n");
      out.write("  border:1px solid #ccc;\r\n");
      out.write("  margin-left:10px;\r\n");
      out.write("  margin-top:22px;\r\n");
      out.write("  color:inherit;\r\n");
      out.write("  opacity:0.75;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-clean .item.social > a:hover {\r\n");
      out.write("  opacity:0.9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width:991px) {\r\n");
      out.write("  .footer-all .item.social > a {\r\n");
      out.write("    margin-top:40px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width:767px) {\r\n");
      out.write("  .footer-all .item.social > a {\r\n");
      out.write("    margin-top:10px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-clean .copyright {\r\n");
      out.write("  margin-top:14px;\r\n");
      out.write("  margin-bottom:0;\r\n");
      out.write("  font-size:13px;\r\n");
      out.write("  opacity:0.6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"footer-clean\">\r\n");
      out.write("    <hr>\r\n");
      out.write("        <footer>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row justify-content-center\">\r\n");
      out.write("                    <div class=\"col-sm-4 col-md-3 item\">\r\n");
      out.write("                        <h3>Home</h3>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">머 넣을가</a></li>\r\n");
      out.write("                            <li><a href=\"#\">머 넣지</a></li>\r\n");
      out.write("                            <li><a href=\"#\">오우 오우</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-4 col-md-3 item\">\r\n");
      out.write("                        <h3>Service</h3>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">고객센터</a></li>\r\n");
      out.write("                            <li><a href=\"#\">커뮤니티</a></li>\r\n");
      out.write("                            <li><a href=\"#\">음음</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-4 col-md-3 item\">\r\n");
      out.write("                        <h3>여기도 머넣지</h3>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">으어</a></li>\r\n");
      out.write("                            <li><a href=\"#\">배고프다</a></li>\r\n");
      out.write("                            <li><a href=\"#\">으엑</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-3 item social\"><a href=\"#\"><i class=\"icon ion-social-facebook\"></i></a><a href=\"#\"><i class=\"icon ion-social-twitter\"></i></a><a href=\"#\"><i class=\"icon ion-social-snapchat\"></i></a><a href=\"#\"><i class=\"icon ion-social-instagram\"></i></a>\r\n");
      out.write("                        <p class=\"copyright\">Topping © 2021</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
